import { useState } from 'react';
import DashboardChart from '../pages/dashboard/DashboardChart.jsx';
import { activities, departments, departmentPeriods, metrics, quickActions, systemStatuses } from './adminPreviewData.js';

export default function AdminPreviewDashboard({ onAction }) {
    const [period, setPeriod] = useState('Last 30 days (sample)');
    const values = departmentPeriods[period];
    return <>
        <div className="admin-welcome"><p className="admin-eyebrow">STAKEHOLDER PREVIEW · SAMPLE DATA</p><h1>Welcome to the CityVUE Admin Portal</h1><p className="text-body-secondary">Configure and manage your resident engagement platform, AI services, and system settings.</p></div>
        <section className="admin-metrics" aria-label="Sample platform metrics">{metrics.map(({ label, value, icon, tone }) => <article className="admin-card admin-metric" key={label}><span className={`admin-metric-icon text-${tone}-emphasis bg-${tone}-subtle`}><i className={`bi bi-${icon}`} aria-hidden="true" /></span><div><h2>{label}</h2><p>{value}</p><small className="text-body-secondary">Sample value</small></div></article>)}</section>
        <div className="admin-dashboard-grid">
            <section className="admin-card admin-activity" aria-labelledby="admin-activity-title"><div className="admin-card-heading"><h2 id="admin-activity-title">Recent Activity</h2><span className="admin-sample-label">Demo records</span></div><div className="admin-table-scroll" role="region" aria-label="Sample recent activity table" tabIndex="0"><table className="table align-middle mb-0"><caption className="visually-hidden">Fictional activity for design review; no production audit data.</caption><thead><tr>{['Date & Time', 'Type', 'Details', 'User'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{activities.map(([date, type, details, user]) => <tr key={type}><td>{date}</td><th scope="row"><span className="admin-type-label">{type}</span></th><td>{details}</td><td>{user}</td></tr>)}</tbody></table></div></section>
            <section className="admin-card" aria-labelledby="admin-status-title"><div className="admin-card-heading"><h2 id="admin-status-title">System Status</h2></div><p className="small text-body-secondary">Demo indicators — not live monitoring.</p><dl className="admin-status-list">{systemStatuses.map(([name, status]) => <div key={name}><dt>{name}</dt><dd className={status === 'Operational' ? 'text-success-emphasis' : 'text-body-secondary'}><i className={`bi bi-${status === 'Operational' ? 'check-circle-fill' : 'dash-circle'}`} aria-hidden="true" /> {status}</dd></div>)}</dl></section>
            <section className="admin-card" aria-labelledby="admin-departments-title"><div className="admin-card-heading"><h2 id="admin-departments-title">Issues by Department</h2><div><label className="visually-hidden" htmlFor="admin-chart-period">Sample chart period</label><select className="form-select form-select-sm" id="admin-chart-period" value={period} onChange={event => setPeriod(event.target.value)}>{Object.keys(departmentPeriods).map(label => <option key={label}>{label}</option>)}</select></div></div><p className="small text-body-secondary">Illustrative subset of sample issues.</p><div className="admin-chart"><DashboardChart type="bar" labels={departments} values={values} label="Sample issues" indexAxis="y" /></div><details className="admin-chart-values"><summary>View chart values</summary><dl>{departments.map((name, index) => <div key={name}><dt>{name}</dt><dd>{values[index]}</dd></div>)}</dl></details></section>
            <section className="admin-card" aria-labelledby="admin-actions-title"><div className="admin-card-heading"><h2 id="admin-actions-title">Quick Actions</h2></div><p className="small text-body-secondary">Explore the proposed workflow. Actions are disabled.</p><div className="admin-quick-actions">{quickActions.map(label => <button className="btn btn-outline-primary text-start" type="button" key={label} onClick={event => onAction(label, event.currentTarget)}><i className="bi bi-arrow-up-right" aria-hidden="true" /> {label}</button>)}</div></section>
            <section className="admin-card admin-ai-overview" aria-labelledby="admin-ai-title"><div className="admin-card-heading"><h2 id="admin-ai-title">AI Usage Overview</h2><span className="admin-sample-label">Preview Mode</span></div><p className="text-body-secondary">AI services are not yet connected. Usage metrics will be available once the AI provider is configured.</p><dl>{['Total Requests', 'Active Users', 'Avg. Response Time'].map(label => <div key={label}><dt>{label}</dt><dd>0</dd></div>)}</dl><p className="small text-body-secondary mb-0">Demo placeholders only; no usage API is connected.</p></section>
        </div>
    </>;
}
